/*
 * (C) Copyright 2016 Rockchip Electronics Co., Ltd
 *
 * SPDX-License-Identifier:     GPL-2.0+
 */

#ifndef __CONFIG_H
#define __CONFIG_H

#define ROCKCHIP_DEVICE_SETTINGS
#include <configs/rk3288_common.h>

#define CONFIG_ENV_IS_NOWHERE

#undef CONFIG_BOARD_LATE_INIT
#undef CONFIG_EXTRA_ENV_SETTINGS
#undef CONFIG_USB_GADGET
#undef CONFIG_USB_FUNCTION_MASS_STORAGE
#undef CONFIG_CMD_FASTBOOT
#undef CONFIG_ROCKCHIP_USB2_PHY
#undef CONFIG_CMD_USB_MASS_STORAGE

#undef CONFIG_SYS_TEXT_BASE
#undef CONFIG_SYS_INIT_SP_ADDR
#undef CONFIG_SYS_SDRAM_BASE
#define CONFIG_SYS_TEXT_BASE		0x50000000
#define CONFIG_SYS_INIT_SP_ADDR		CONFIG_SYS_TEXT_BASE
#define CONFIG_SYS_SDRAM_BASE		CONFIG_SYS_TEXT_BASE

#undef CONFIG_SYS_TIMER_BASE
#define	CONFIG_SYS_TIMER_BASE		0xff810020 /* TIMER7 */

#define SDRAM_SIZE	0x10000000

#undef CONFIG_BOOTDELAY
#define CONFIG_BOOTDELAY		-1



#endif
