#!/bin/bash
set -e

echo    "******************************"
echo    "*     make board config      *"
echo    "******************************"
make rk32xx_config

echo    "******************************"
echo    "*     make rkuboot.bin       *"
echo    "******************************"
make --jobs=`sed -n "N;/processor/p" /proc/cpuinfo|wc -l`

