#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += android.o
obj-y += boringssl_ed25519_ops.o
obj-y += cbor_reader.o
obj-y += cbor_writer.o
obj-y += cbor_cert_op.o
obj-y += clear_memory.o
obj-y += dice.o
obj-y += dice_main.o
obj-y += mbedtls_ops.o
obj-y += utils.o
