#********************************************************************************
#		COPYRIGHT (c)   2013 BY ROCK-CHIP FUZHOU
#			--  ALL RIGHTS RESERVED  --
#File Name:	
#Author:         
#Created:        
#Modified:
#Revision:       1.00
#********************************************************************************

obj-y := $(BOARD).o
obj-y += crc.o
obj-y += rkimage.o
obj-y += rkloader.o
obj-y += fastboot.o
