#********************************************************************************
#		COPYRIGHT (c)   2013 BY ROCK-CHIP FUZHOU
#			--  ALL RIGHTS RESERVED  --
#File Name:	
#Author:         
#Created:        
#Modified:
#Revision:       1.00
#********************************************************************************

obj-y := $(BOARD).o
obj-y += crc.o
obj-y += rkimage.o
obj-y += rkloader.o
obj-y += fastboot.o
obj-y += ddr.o
#obj-y += armlinux/armlinux.o
obj-$(CONFIG_ZYF) += bootloader.o
obj-$(CONFIG_ZYF) += enter_recovery.o
#obj-y += armlinux/Mainloop.o
obj-$(CONFIG_ZYF) += mtdpart.o
obj-$(CONFIG_ZYF) += parameter.o
#obj-y += armlinux/session.o
#obj-y += armlinux/rk28_kld.o
#obj-y += common/A8MMU/CacheCleanFlushRegion.o
#obj-y += common/A8MMU/CacheCleanFlushWay.o
#obj-y += common/A8MMU/CacheCleanFlushWhole.o
#obj-y += common/A8MMU/CacheControl.o
#obj-y += common/A8MMU/CacheLock.o
obj-$(CONFIG_ZYF) += hw_mm.o
#obj-y += common/A8MMU/MMU.o
#obj-y += common/A8MMU/MMUControl.o
#obj-y += common/A8MMU/MMUOperateTLB.o
#obj-y += common/A8MMU/pl310_l2cc.o
#obj-y += common/A8MMU/RK30CacheCleanFlushWhole.o
#obj-y += common/crc/ldcrc.o
#obj-y += common/crc/ldcrctable.o
obj-$(CONFIG_ZYF) += rsa.o
obj-$(CONFIG_ZYF) += sha.o
obj-$(CONFIG_ZYF) += emmc/hw_MMC.o
obj-$(CONFIG_ZYF) += emmc/hw_SD.o
obj-$(CONFIG_ZYF) += emmc/hw_SDController.o
obj-$(CONFIG_ZYF) += emmc/hw_SDM.o
obj-$(CONFIG_ZYF) += emmc/hw_SDOsAdapt.o
obj-$(CONFIG_ZYF) += emmc/hw_SDPlatAdapt.o
obj-$(CONFIG_ZYF) += emmc/sdmmcBoot.o
#obj-y += common/fat/chkdsk.o
#obj-y += common/fat/dir.o
#obj-y += common/fat/Drive.o
#obj-y += common/fat/fat.o
#obj-y += common/fat/FDT.o
#obj-y += common/fat/file.o
obj-$(CONFIG_ZYF) += rc4.o
obj-$(CONFIG_ZYF) += rc4_enc.o
obj-$(CONFIG_ZYF) += rockusb/Chap_9.o
obj-$(CONFIG_ZYF) += rockusb/D12ci.o
obj-$(CONFIG_ZYF) += rockusb/rockusb.o
obj-$(CONFIG_ZYF) += rockusb/usbCtrl.o
obj-$(CONFIG_ZYF) += rockusb/usbIsr.o
#obj-y += common/serial_p9/serial.o
#obj-y += common/SPI/SpiBoot.o
#obj-y += common/SPI/SpiFlash.o
obj-$(CONFIG_ZYF) += boot.o
obj-$(CONFIG_ZYF) += GetIdBlockInfo.o
#obj-y += common/loaderTag.o
obj-$(CONFIG_ZYF) += std_commod.o
obj-$(CONFIG_ZYF) += storage.o
obj-$(CONFIG_ZYF) += chipDepend.o
obj-$(CONFIG_ZYF) += gpio_oper.o
obj-$(CONFIG_ZYF) += Isr.o
##obj-y += platform/rk30/regdump.o
##obj-y += platform/rk30/romloader.o
##obj-y += platform/rk30/start.o
#obj-$(CONFIG_ZYF) += platform/rk30/timer.o
##obj-y += platform/rk30/uart.o
##obj-y += dummy.o
