# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2017 Linaro Limited

obj-y += avb_chain_partition_descriptor.o avb_cmdline.o avb_crc32.o \
	 avb_crypto.o avb_footer.o avb_hashtree_descriptor.o \
	 avb_property_descriptor.o avb_sha256.o \
	 avb_slot_verify.o avb_util.o avb_version.o \
	 avb_descriptor.o avb_hash_descriptor.o \
	 avb_kernel_cmdline_descriptor.o avb_rsa.o avb_sha512.o \
	 avb_sysdeps_posix.o avb_vbmeta_image.o

ccflags-y = -DAVB_COMPILATION
