/*
 * (C) Copyright 2008-2014 Rockchip Electronics
 * Peter, Software Engineering, <superpeter.cai@gmail.com>.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 *
 */
#ifndef __RK3288_GPIO_H
#define __RK3288_GPIO_H


/* gpio banks defined */
#define GPIO_BANKS		9

#define NUM_GROUP		32
#define MAX_GPIO_NUM		(NUM_GROUP * GPIO_BANKS)

/* if define irq, PIN_BASE start from NR_GIC_IRQS */
#ifdef CONFIG_USE_IRQ
	#define PIN_BASE	NR_GIC_IRQS
#else
	#define PIN_BASE	0
#endif /* CONFIG_USE_RKIRQ */

#define INVALID_GPIO        	-1

/* total 160 gpio pin */
#define	RKXX_PIN0_PA0		(0*NUM_GROUP + PIN_BASE + 0)
#define	RKXX_PIN0_PA1		(0*NUM_GROUP + PIN_BASE + 1)
#define	RKXX_PIN0_PA2		(0*NUM_GROUP + PIN_BASE + 2)
#define	RKXX_PIN0_PA3		(0*NUM_GROUP + PIN_BASE + 3)
#define	RKXX_PIN0_PA4		(0*NUM_GROUP + PIN_BASE + 4)
#define	RKXX_PIN0_PA5		(0*NUM_GROUP + PIN_BASE + 5)
#define	RKXX_PIN0_PA6		(0*NUM_GROUP + PIN_BASE + 6)
#define	RKXX_PIN0_PA7		(0*NUM_GROUP + PIN_BASE + 7)
#define	RKXX_PIN0_PB0		(0*NUM_GROUP + PIN_BASE + 8)
#define	RKXX_PIN0_PB1		(0*NUM_GROUP + PIN_BASE + 9)
#define	RKXX_PIN0_PB2		(0*NUM_GROUP + PIN_BASE + 10)
#define	RKXX_PIN0_PB3		(0*NUM_GROUP + PIN_BASE + 11)
#define	RKXX_PIN0_PB4		(0*NUM_GROUP + PIN_BASE + 12)
#define	RKXX_PIN0_PB5		(0*NUM_GROUP + PIN_BASE + 13)
#define	RKXX_PIN0_PB6		(0*NUM_GROUP + PIN_BASE + 14)
#define	RKXX_PIN0_PB7		(0*NUM_GROUP + PIN_BASE + 15)
#define	RKXX_PIN0_PC0		(0*NUM_GROUP + PIN_BASE + 16)
#define	RKXX_PIN0_PC1		(0*NUM_GROUP + PIN_BASE + 17)
#define	RKXX_PIN0_PC2		(0*NUM_GROUP + PIN_BASE + 18)
#define	RKXX_PIN0_PC3		INVALID_GPIO
#define	RKXX_PIN0_PC4		INVALID_GPIO
#define	RKXX_PIN0_PC5		INVALID_GPIO
#define	RKXX_PIN0_PC6		INVALID_GPIO
#define	RKXX_PIN0_PC7		INVALID_GPIO
#define	RKXX_PIN0_PD0		INVALID_GPIO
#define	RKXX_PIN0_PD1		INVALID_GPIO
#define	RKXX_PIN0_PD2		INVALID_GPIO
#define	RKXX_PIN0_PD3		INVALID_GPIO
#define	RKXX_PIN0_PD4		INVALID_GPIO
#define	RKXX_PIN0_PD5		INVALID_GPIO
#define	RKXX_PIN0_PD6		INVALID_GPIO
#define	RKXX_PIN0_PD7		INVALID_GPIO

#define	RKXX_PIN1_PA0		INVALID_GPIO
#define	RKXX_PIN1_PA1		INVALID_GPIO
#define	RKXX_PIN1_PA2		INVALID_GPIO
#define	RKXX_PIN1_PA3		INVALID_GPIO
#define	RKXX_PIN1_PA4		INVALID_GPIO
#define	RKXX_PIN1_PA5		INVALID_GPIO
#define	RKXX_PIN1_PA6		INVALID_GPIO
#define	RKXX_PIN1_PA7		INVALID_GPIO
#define	RKXX_PIN1_PB0		INVALID_GPIO
#define	RKXX_PIN1_PB1		INVALID_GPIO
#define	RKXX_PIN1_PB2		INVALID_GPIO
#define	RKXX_PIN1_PB3		INVALID_GPIO
#define	RKXX_PIN1_PB4		INVALID_GPIO
#define	RKXX_PIN1_PB5		INVALID_GPIO
#define	RKXX_PIN1_PB6		INVALID_GPIO
#define	RKXX_PIN1_PB7		INVALID_GPIO
#define	RKXX_PIN1_PC0		INVALID_GPIO
#define	RKXX_PIN1_PC1		INVALID_GPIO
#define	RKXX_PIN1_PC2		INVALID_GPIO
#define	RKXX_PIN1_PC3		INVALID_GPIO
#define	RKXX_PIN1_PC4		INVALID_GPIO
#define	RKXX_PIN1_PC5		INVALID_GPIO
#define	RKXX_PIN1_PC6		INVALID_GPIO
#define	RKXX_PIN1_PC7		INVALID_GPIO
#define	RKXX_PIN1_PD0		(1*NUM_GROUP + PIN_BASE + 24)
#define	RKXX_PIN1_PD1		(1*NUM_GROUP + PIN_BASE + 25)
#define	RKXX_PIN1_PD2		(1*NUM_GROUP + PIN_BASE + 26)
#define	RKXX_PIN1_PD3		(1*NUM_GROUP + PIN_BASE + 27)
#define	RKXX_PIN1_PD4		INVALID_GPIO
#define	RKXX_PIN1_PD5		INVALID_GPIO
#define	RKXX_PIN1_PD6		INVALID_GPIO
#define	RKXX_PIN1_PD7		INVALID_GPIO

#define	RKXX_PIN2_PA0		(2*NUM_GROUP + PIN_BASE + 0)
#define	RKXX_PIN2_PA1		(2*NUM_GROUP + PIN_BASE + 1)
#define	RKXX_PIN2_PA2		(2*NUM_GROUP + PIN_BASE + 2)
#define	RKXX_PIN2_PA3		(2*NUM_GROUP + PIN_BASE + 3)
#define	RKXX_PIN2_PA4		(2*NUM_GROUP + PIN_BASE + 4)
#define	RKXX_PIN2_PA5		(2*NUM_GROUP + PIN_BASE + 5)
#define	RKXX_PIN2_PA6		(2*NUM_GROUP + PIN_BASE + 6)
#define	RKXX_PIN2_PA7		(2*NUM_GROUP + PIN_BASE + 7)
#define	RKXX_PIN2_PB0		(2*NUM_GROUP + PIN_BASE + 8)
#define	RKXX_PIN2_PB1		(2*NUM_GROUP + PIN_BASE + 9)
#define	RKXX_PIN2_PB2		(2*NUM_GROUP + PIN_BASE + 10)
#define	RKXX_PIN2_PB3		(2*NUM_GROUP + PIN_BASE + 11)
#define	RKXX_PIN2_PB4		(2*NUM_GROUP + PIN_BASE + 12)
#define	RKXX_PIN2_PB5		(2*NUM_GROUP + PIN_BASE + 13)
#define	RKXX_PIN2_PB6		(2*NUM_GROUP + PIN_BASE + 14)
#define	RKXX_PIN2_PB7		(2*NUM_GROUP + PIN_BASE + 15)
#define	RKXX_PIN2_PC0		(2*NUM_GROUP + PIN_BASE + 16)
#define	RKXX_PIN2_PC1		(2*NUM_GROUP + PIN_BASE + 17)
#define	RKXX_PIN2_PC2		INVALID_GPIO
#define	RKXX_PIN2_PC3		INVALID_GPIO
#define	RKXX_PIN2_PC4		INVALID_GPIO
#define	RKXX_PIN2_PC5		INVALID_GPIO
#define	RKXX_PIN2_PC6		INVALID_GPIO
#define	RKXX_PIN2_PC7		INVALID_GPIO
#define	RKXX_PIN2_PD0		INVALID_GPIO
#define	RKXX_PIN2_PD1		INVALID_GPIO
#define	RKXX_PIN2_PD2		INVALID_GPIO
#define	RKXX_PIN2_PD3		INVALID_GPIO
#define	RKXX_PIN2_PD4		INVALID_GPIO
#define	RKXX_PIN2_PD5		INVALID_GPIO
#define	RKXX_PIN2_PD6		INVALID_GPIO
#define	RKXX_PIN2_PD7		INVALID_GPIO

#define	RKXX_PIN3_PA0		(3*NUM_GROUP + PIN_BASE + 0)
#define	RKXX_PIN3_PA1		(3*NUM_GROUP + PIN_BASE + 1)
#define	RKXX_PIN3_PA2		(3*NUM_GROUP + PIN_BASE + 2)
#define	RKXX_PIN3_PA3		(3*NUM_GROUP + PIN_BASE + 3)
#define	RKXX_PIN3_PA4		(3*NUM_GROUP + PIN_BASE + 4)
#define	RKXX_PIN3_PA5		(3*NUM_GROUP + PIN_BASE + 5)
#define	RKXX_PIN3_PA6		(3*NUM_GROUP + PIN_BASE + 6)
#define	RKXX_PIN3_PA7		(3*NUM_GROUP + PIN_BASE + 7)
#define	RKXX_PIN3_PB0		(3*NUM_GROUP + PIN_BASE + 8)
#define	RKXX_PIN3_PB1		(3*NUM_GROUP + PIN_BASE + 9)
#define	RKXX_PIN3_PB2		(3*NUM_GROUP + PIN_BASE + 10)
#define	RKXX_PIN3_PB3		(3*NUM_GROUP + PIN_BASE + 11)
#define	RKXX_PIN3_PB4		(3*NUM_GROUP + PIN_BASE + 12)
#define	RKXX_PIN3_PB5		(3*NUM_GROUP + PIN_BASE + 13)
#define	RKXX_PIN3_PB6		(3*NUM_GROUP + PIN_BASE + 14)
#define	RKXX_PIN3_PB7		(3*NUM_GROUP + PIN_BASE + 15)
#define	RKXX_PIN3_PC0		(3*NUM_GROUP + PIN_BASE + 16)
#define	RKXX_PIN3_PC1		(3*NUM_GROUP + PIN_BASE + 17)
#define	RKXX_PIN3_PC2		(3*NUM_GROUP + PIN_BASE + 18)
#define	RKXX_PIN3_PC3		(3*NUM_GROUP + PIN_BASE + 19)
#define	RKXX_PIN3_PC4		INVALID_GPIO
#define	RKXX_PIN3_PC5		INVALID_GPIO
#define	RKXX_PIN3_PC6		INVALID_GPIO
#define	RKXX_PIN3_PC7		INVALID_GPIO
#define	RKXX_PIN3_PD0		(3*NUM_GROUP + PIN_BASE + 24)
#define	RKXX_PIN3_PD1		(3*NUM_GROUP + PIN_BASE + 25)
#define	RKXX_PIN3_PD2		(3*NUM_GROUP + PIN_BASE + 26)
#define	RKXX_PIN3_PD3		(3*NUM_GROUP + PIN_BASE + 27)
#define	RKXX_PIN3_PD4		(3*NUM_GROUP + PIN_BASE + 28)
#define	RKXX_PIN3_PD5		(3*NUM_GROUP + PIN_BASE + 29)
#define	RKXX_PIN3_PD6		(3*NUM_GROUP + PIN_BASE + 30)
#define	RKXX_PIN3_PD7		(3*NUM_GROUP + PIN_BASE + 31)

#define	RKXX_PIN4_PA0		(4*NUM_GROUP + PIN_BASE + 0)
#define	RKXX_PIN4_PA1		(4*NUM_GROUP + PIN_BASE + 1)
#define	RKXX_PIN4_PA2		(4*NUM_GROUP + PIN_BASE + 2)
#define	RKXX_PIN4_PA3		(4*NUM_GROUP + PIN_BASE + 3)
#define	RKXX_PIN4_PA4		(4*NUM_GROUP + PIN_BASE + 4)
#define	RKXX_PIN4_PA5		(4*NUM_GROUP + PIN_BASE + 5)
#define	RKXX_PIN4_PA6		(4*NUM_GROUP + PIN_BASE + 6)
#define	RKXX_PIN4_PA7		(4*NUM_GROUP + PIN_BASE + 7)
#define	RKXX_PIN4_PB0		(4*NUM_GROUP + PIN_BASE + 8)
#define	RKXX_PIN4_PB1		(4*NUM_GROUP + PIN_BASE + 9)
#define	RKXX_PIN4_PB2		INVALID_GPIO
#define	RKXX_PIN4_PB3		INVALID_GPIO
#define	RKXX_PIN4_PB4		INVALID_GPIO
#define	RKXX_PIN4_PB5		INVALID_GPIO
#define	RKXX_PIN4_PB6		INVALID_GPIO
#define	RKXX_PIN4_PB7		INVALID_GPIO
#define	RKXX_PIN4_PC0		(4*NUM_GROUP + PIN_BASE + 16)
#define	RKXX_PIN4_PC1		(4*NUM_GROUP + PIN_BASE + 17)
#define	RKXX_PIN4_PC2		(4*NUM_GROUP + PIN_BASE + 18)
#define	RKXX_PIN4_PC3		(4*NUM_GROUP + PIN_BASE + 19)
#define	RKXX_PIN4_PC4		(4*NUM_GROUP + PIN_BASE + 20)
#define	RKXX_PIN4_PC5		(4*NUM_GROUP + PIN_BASE + 21)
#define	RKXX_PIN4_PC6		(4*NUM_GROUP + PIN_BASE + 22)
#define	RKXX_PIN4_PC7		(4*NUM_GROUP + PIN_BASE + 23)
#define	RKXX_PIN4_PD0		(4*NUM_GROUP + PIN_BASE + 24)
#define	RKXX_PIN4_PD1		(4*NUM_GROUP + PIN_BASE + 25)
#define	RKXX_PIN4_PD2		(4*NUM_GROUP + PIN_BASE + 26)
#define	RKXX_PIN4_PD3		(4*NUM_GROUP + PIN_BASE + 27)
#define	RKXX_PIN4_PD4		(4*NUM_GROUP + PIN_BASE + 28)
#define	RKXX_PIN4_PD5		(4*NUM_GROUP + PIN_BASE + 29)
#define	RKXX_PIN4_PD6		(4*NUM_GROUP + PIN_BASE + 30)
#define	RKXX_PIN4_PD7		(4*NUM_GROUP + PIN_BASE + 31)

#define	RKXX_PIN5_PA0		INVALID_GPIO
#define	RKXX_PIN5_PA1		INVALID_GPIO
#define	RKXX_PIN5_PA2		INVALID_GPIO
#define	RKXX_PIN5_PA3		INVALID_GPIO
#define	RKXX_PIN5_PA4		INVALID_GPIO
#define	RKXX_PIN5_PA5		INVALID_GPIO
#define	RKXX_PIN5_PA6		INVALID_GPIO
#define	RKXX_PIN5_PA7		INVALID_GPIO
#define	RKXX_PIN5_PB0		(5*NUM_GROUP + PIN_BASE + 8)
#define	RKXX_PIN5_PB1		(5*NUM_GROUP + PIN_BASE + 9)
#define	RKXX_PIN5_PB2		(5*NUM_GROUP + PIN_BASE + 10)
#define	RKXX_PIN5_PB3		(5*NUM_GROUP + PIN_BASE + 11)
#define	RKXX_PIN5_PB4		(5*NUM_GROUP + PIN_BASE + 12)
#define	RKXX_PIN5_PB5		(5*NUM_GROUP + PIN_BASE + 13)
#define	RKXX_PIN5_PB6		(5*NUM_GROUP + PIN_BASE + 14)
#define	RKXX_PIN5_PB7		(5*NUM_GROUP + PIN_BASE + 15)
#define	RKXX_PIN5_PC0		(5*NUM_GROUP + PIN_BASE + 16)
#define	RKXX_PIN5_PC1		(5*NUM_GROUP + PIN_BASE + 17)
#define	RKXX_PIN5_PC2		(5*NUM_GROUP + PIN_BASE + 18)
#define	RKXX_PIN5_PC3		(5*NUM_GROUP + PIN_BASE + 19)
#define	RKXX_PIN5_PD0		INVALID_GPIO
#define	RKXX_PIN5_PD1		INVALID_GPIO
#define	RKXX_PIN5_PD2		INVALID_GPIO
#define	RKXX_PIN5_PD3		INVALID_GPIO
#define	RKXX_PIN5_PD4		INVALID_GPIO
#define	RKXX_PIN5_PD5		INVALID_GPIO
#define	RKXX_PIN5_PD6		INVALID_GPIO
#define	RKXX_PIN5_PD7		INVALID_GPIO

#define	RKXX_PIN6_PA0		(6*NUM_GROUP + PIN_BASE + 0)
#define	RKXX_PIN6_PA1		(6*NUM_GROUP + PIN_BASE + 1)
#define	RKXX_PIN6_PA2		(6*NUM_GROUP + PIN_BASE + 2)
#define	RKXX_PIN6_PA3		(6*NUM_GROUP + PIN_BASE + 3)
#define	RKXX_PIN6_PA4		(6*NUM_GROUP + PIN_BASE + 4)
#define	RKXX_PIN6_PA5		(6*NUM_GROUP + PIN_BASE + 5)
#define	RKXX_PIN6_PA6		(6*NUM_GROUP + PIN_BASE + 6)
#define	RKXX_PIN6_PA7		(6*NUM_GROUP + PIN_BASE + 7)
#define	RKXX_PIN6_PB0		(6*NUM_GROUP + PIN_BASE + 8)
#define	RKXX_PIN6_PB1		(6*NUM_GROUP + PIN_BASE + 9)
#define	RKXX_PIN6_PB2		(6*NUM_GROUP + PIN_BASE + 10)
#define	RKXX_PIN6_PB3		(6*NUM_GROUP + PIN_BASE + 11)
#define	RKXX_PIN6_PB4		INVALID_GPIO
#define	RKXX_PIN6_PB5		INVALID_GPIO
#define	RKXX_PIN6_PB6		INVALID_GPIO
#define	RKXX_PIN6_PB7		INVALID_GPIO
#define	RKXX_PIN6_PC0		(6*NUM_GROUP + PIN_BASE + 16)
#define	RKXX_PIN6_PC1		(6*NUM_GROUP + PIN_BASE + 17)
#define	RKXX_PIN6_PC2		(6*NUM_GROUP + PIN_BASE + 18)
#define	RKXX_PIN6_PC3		(6*NUM_GROUP + PIN_BASE + 19)
#define	RKXX_PIN6_PC4		(6*NUM_GROUP + PIN_BASE + 20)
#define	RKXX_PIN6_PC5		(6*NUM_GROUP + PIN_BASE + 21)
#define	RKXX_PIN6_PC6		(6*NUM_GROUP + PIN_BASE + 22)
#define	RKXX_PIN6_PC7		INVALID_GPIO
#define	RKXX_PIN6_PD0		INVALID_GPIO
#define	RKXX_PIN6_PD1		INVALID_GPIO
#define	RKXX_PIN6_PD2		INVALID_GPIO
#define	RKXX_PIN6_PD3		INVALID_GPIO
#define	RKXX_PIN6_PD4		INVALID_GPIO
#define	RKXX_PIN6_PD5		INVALID_GPIO
#define	RKXX_PIN6_PD6		INVALID_GPIO
#define	RKXX_PIN6_PD7		INVALID_GPIO

#define	RKXX_PIN7_PA0		(7*NUM_GROUP + PIN_BASE + 0)
#define	RKXX_PIN7_PA1		(7*NUM_GROUP + PIN_BASE + 1)
#define	RKXX_PIN7_PA2		(7*NUM_GROUP + PIN_BASE + 2)
#define	RKXX_PIN7_PA3		(7*NUM_GROUP + PIN_BASE + 3)
#define	RKXX_PIN7_PA4		(7*NUM_GROUP + PIN_BASE + 4)
#define	RKXX_PIN7_PA5		(7*NUM_GROUP + PIN_BASE + 5)
#define	RKXX_PIN7_PA6		(7*NUM_GROUP + PIN_BASE + 6)
#define	RKXX_PIN7_PA7		(7*NUM_GROUP + PIN_BASE + 7)
#define	RKXX_PIN7_PB0		(7*NUM_GROUP + PIN_BASE + 8)
#define	RKXX_PIN7_PB1		(7*NUM_GROUP + PIN_BASE + 9)
#define	RKXX_PIN7_PB2		(7*NUM_GROUP + PIN_BASE + 10)
#define	RKXX_PIN7_PB3		(7*NUM_GROUP + PIN_BASE + 11)
#define	RKXX_PIN7_PB4		(7*NUM_GROUP + PIN_BASE + 12)
#define	RKXX_PIN7_PB5		(7*NUM_GROUP + PIN_BASE + 13)
#define	RKXX_PIN7_PB6		(7*NUM_GROUP + PIN_BASE + 14)
#define	RKXX_PIN7_PB7		(7*NUM_GROUP + PIN_BASE + 15)
#define	RKXX_PIN7_PC0		(7*NUM_GROUP + PIN_BASE + 16)
#define	RKXX_PIN7_PC1		(7*NUM_GROUP + PIN_BASE + 17)
#define	RKXX_PIN7_PC2		(7*NUM_GROUP + PIN_BASE + 18)
#define	RKXX_PIN7_PC3		(7*NUM_GROUP + PIN_BASE + 19)
#define	RKXX_PIN7_PC4		(7*NUM_GROUP + PIN_BASE + 20)
#define	RKXX_PIN7_PC5		(7*NUM_GROUP + PIN_BASE + 21)
#define	RKXX_PIN7_PC6		(7*NUM_GROUP + PIN_BASE + 22)
#define	RKXX_PIN7_PC7		(7*NUM_GROUP + PIN_BASE + 23)
#define	RKXX_PIN7_PD0		INVALID_GPIO
#define	RKXX_PIN7_PD1		INVALID_GPIO
#define	RKXX_PIN7_PD2		INVALID_GPIO
#define	RKXX_PIN7_PD3		INVALID_GPIO
#define	RKXX_PIN7_PD4		INVALID_GPIO
#define	RKXX_PIN7_PD5		INVALID_GPIO
#define	RKXX_PIN7_PD6		INVALID_GPIO
#define	RKXX_PIN7_PD7		INVALID_GPIO

#define	RKXX_PIN8_PA0		(8*NUM_GROUP + PIN_BASE + 0)
#define	RKXX_PIN8_PA1		(8*NUM_GROUP + PIN_BASE + 1)
#define	RKXX_PIN8_PA2		(8*NUM_GROUP + PIN_BASE + 2)
#define	RKXX_PIN8_PA3		(8*NUM_GROUP + PIN_BASE + 3)
#define	RKXX_PIN8_PA4		(8*NUM_GROUP + PIN_BASE + 4)
#define	RKXX_PIN8_PA5		(8*NUM_GROUP + PIN_BASE + 5)
#define	RKXX_PIN8_PA6		(8*NUM_GROUP + PIN_BASE + 6)
#define	RKXX_PIN8_PA7		(8*NUM_GROUP + PIN_BASE + 7)
#define	RKXX_PIN8_PB0		(8*NUM_GROUP + PIN_BASE + 8)
#define	RKXX_PIN8_PB1		(8*NUM_GROUP + PIN_BASE + 9)
#define	RKXX_PIN8_PB2		INVALID_GPIO
#define	RKXX_PIN8_PB3		INVALID_GPIO
#define	RKXX_PIN8_PB4		INVALID_GPIO
#define	RKXX_PIN8_PB5		INVALID_GPIO
#define	RKXX_PIN8_PB6		INVALID_GPIO
#define	RKXX_PIN8_PB7		INVALID_GPIO

#define PIN_MAX			RKXX_PIN8_PB1


/* rk gpio banks data only for gpio driver module */
#ifdef RK_GPIO_DRIVER_MODULE
#define RK_GPIO_BANK(ID)			\
	{								\
		.regbase = (unsigned char __iomem *) RKIO_GPIO##ID##_PHYS, \
		.id = ID,	\
		.base             = PIN_BASE + ID*NUM_GROUP,	\
		.ngpio            = NUM_GROUP,	\
	}

static struct rk_gpio_bank rk_gpio_banks[GPIO_BANKS] = {
	RK_GPIO_BANK(0),
	RK_GPIO_BANK(1),
	RK_GPIO_BANK(2),
	RK_GPIO_BANK(3),
	RK_GPIO_BANK(4),
	RK_GPIO_BANK(5),
	RK_GPIO_BANK(6),
	RK_GPIO_BANK(7),
	RK_GPIO_BANK(8)
};
#endif /* RK_GPIO_BANKS_DATA */

#endif	/* __RK3288_GPIO_H */

