#
# Copyright (C) 2012 Samsung Electronics
# Lukasz Majewski <l.majewski@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_POWER_FG_MAX17042) += fg_max17042.o
obj-$(CONFIG_POWER_FG_CW201X) += fg_cw201x.o
obj-$(CONFIG_POWER_RICOH619) += fg_ricoh619.o
obj-$(CONFIG_POWER_RK818) += fg_rk818.o
obj-$(CONFIG_POWER_RK818) += fg_rk816.o
obj-$(CONFIG_POWER_RT5025) += fg_rt5025.o
obj-$(CONFIG_POWER_RT5036) += fg_rt5036.o
obj-$(CONFIG_POWER_FG_ADC) += fg_adc.o
