/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2025 Rockchip Electronics Co. Ltd.
 * Author: Elaine Zhang <zhangqing@rock-chips.com>
 */

#ifndef _ASM_ARCH_CRU_RK3572_H
#define _ASM_ARCH_CRU_RK3572_H

#define MHz		1000000
#define KHz		1000
#define OSC_HZ		(24 * MHz)

#define CPU_PVTPLL_HZ		(1008 * MHz)
#define LPLL_HZ			(1008 * MHz)
#define GPLL_HZ			(1188 * MHz)
#define CPLL_HZ			(1000 * MHz)
#define PPLL_HZ			(1300 * MHz)
#define AUPLL_HZ		(786432000)
#define GMAC0_PTP_REFCLK_IN	(24 * MHz)
#define GMAC1_PTP_REFCLK_IN	(24 * MHz)

/* RK3572 pll id */
enum rk3572_pll_id {
	BPLL,
	LPLL,
	DPLL,
	CPLL,
	GPLL,
	VPLL,
	AUPLL,
	SPLL,
	PPLL,
	PLL_COUNT,
};

struct rk3572_clk_info {
	unsigned long id;
	char *name;
	bool is_cru;
};

struct rk3572_clk_priv {
	struct rk3572_cru *cru;
	struct rk3572_grf *grf;
	ulong ppll_hz;
	ulong gpll_hz;
	ulong cpll_hz;
	ulong vpll_hz;
	ulong aupll_hz;
	ulong spll_hz;
	ulong lpll_hz;
	ulong bpll_hz;
	ulong armclk_hz;
	ulong armclk_enter_hz;
	ulong armclk_init_hz;
	bool sync_kernel;
	bool set_armclk_rate;
};

struct rk3572_pll {
	unsigned int con0;
	unsigned int con1;
	unsigned int con2;
	unsigned int con3;
	unsigned int con4;
	unsigned int reserved0[3];
};

struct rk3572_cru {
	unsigned int reserved0[192];
	unsigned int clksel_con[207];
	unsigned int reserved1[113];
	unsigned int clkgate_con[94];
	unsigned int reserved2[34];
	unsigned int softrst_con[88];
	unsigned int reserved3[40];
	unsigned int glb_cnt_th;
	unsigned int glb_rst_st;
	unsigned int glb_srst_fst;
	unsigned int glb_srsr_snd;
	unsigned int glb_rst_con;
	unsigned int reserved4[3323];
	struct rk3572_pll pll[16];
	unsigned int reserved5[32];
	unsigned int mode_con0;
	unsigned int mode_con1;
	unsigned int reserved6[4062];
	struct rk3572_pll ppll[1];
	unsigned int reserved7[56];
	unsigned int phpclksel_con[4];
	unsigned int reserved8[316];
	unsigned int phpclkgate_con[3];
	unsigned int reserved9[125];
	unsigned int phpsoftrst_con[3];
	unsigned int reserved10[24125];
	unsigned int pmuclksel_con[23];
	unsigned int reserved11[297];
	unsigned int pmuclkgate_con[8];
	unsigned int reserved12[120];
	unsigned int pmusoftrst_con[8];
};
check_member(rk3572_cru, clksel_con[0], 0x300);
check_member(rk3572_cru, glb_cnt_th, 0xc00);
check_member(rk3572_cru, phpclksel_con[0], 0x8300);
check_member(rk3572_cru, pmuclksel_con[0], 0x20300);

struct pll_rate_table {
	unsigned long rate;
	unsigned int m;
	unsigned int p;
	unsigned int s;
	unsigned int k;
};

#define RK3572_CRU_BASE			0x26090000
#define RK3572_SCRU_BASE		0x260a0000
#define RK3572_PHP_CRU_BASE		0x8000
#define RK3572_SECURE_NS_CRU_BASE	0x10000
#define RK3572_PMU_CRU_BASE		0x20000
#define RK3572_BIGCORE_CRU_BASE		0x40000
#define RK3572_LITCORE0_CRU_BASE	0x48000
#define RK3572_LITCORE1_CRU_BASE	0x50000
#define RK3572_CCI_CRU_BASE		0x58000

#define RK3572_PLL_CON(x)		((x) * 0x4 + 0x4000)
#define RK3572_MODE_CON0		0x4280
#define RK3572_MODE_CON1		0x4284
#define RK3572_CLKSEL_CON(x)		((x) * 0x4 + 0x300)
#define RK3572_CLKGATE_CON(x)		((x) * 0x4 + 0x800)
#define RK3572_SOFTRST_CON(x)		((x) * 0x4 + 0xa00)
#define RK3572_GLB_CNT_TH		0xc00
#define RK3572_GLB_SRST_FST		0xc08
#define RK3572_GLB_SRST_SND		0xc0c
#define RK3572_GLB_RST_CON		0xc10
#define RK3572_GLB_RST_ST		0xc04

#define RK3572_PPLL_CON(x)		((x) * 0x4 + RK3572_PHP_CRU_BASE)
#define RK3572_PHP_CLKSEL_CON(x)	((x) * 0x4 + RK3572_PHP_CRU_BASE + 0x300)
#define RK3572_PHP_CLKGATE_CON(x)	((x) * 0x4 + RK3572_PHP_CRU_BASE + 0x800)
#define RK3572_PHP_SOFTRST_CON(x)	((x) * 0x4 + RK3572_PHP_CRU_BASE + 0xa00)

#define RK3572_PMU_CLKSEL_CON(x)	((x) * 0x4 + RK3572_PMU_CRU_BASE + 0x300)
#define RK3572_PMU_CLKGATE_CON(x)	((x) * 0x4 + RK3572_PMU_CRU_BASE + 0x800)
#define RK3572_PMU_SOFTRST_CON(x)	((x) * 0x4 + RK3572_PMU_CRU_BASE + 0xa00)

#define RK3572_SECURE_NS_CLKSEL_CON(x)	((x) * 0x4 + RK3572_SECURE_NS_CRU_BASE + 0x300)
#define RK3572_SECURE_NS_CLKGATE_CON(x)	((x) * 0x4 + RK3572_SECURE_NS_CRU_BASE + 0x800)
#define RK3572_SECURE_NS_SOFTRST_CON(x)	((x) * 0x4 + RK3572_SECURE_NS_CRU_BASE + 0xa00)

#define RK3572_LPLL_CON(x)		((x) * 0x4 + RK3572_CCI_CRU_BASE)
#define RK3572_LPLL_MODE_CON0		(0x280 + RK3572_CCI_CRU_BASE)
#define RK3572_CCI_CLKSEL_CON(x)	((x) * 0x4 + RK3572_CCI_CRU_BASE + 0x300)
#define RK3572_CCI_CLKGATE_CON(x)	((x) * 0x4 + RK3572_CCI_CRU_BASE + 0x800)
#define RK3572_CCI_SOFTRST_CON(x)	((x) * 0x4 + RK3572_CCI_CRU_BASE + 0xa00)
#define RK3572_CCI2LITCORE0_RSTCON	(0xc70 + RK3572_CCI_CRU_BASE)
#define RK3572_CCI2LITCORE1_RSTCON	(0xc74 + RK3572_CCI_CRU_BASE)

#define RK3572_BIGCORE_CLKSEL_CON(x)	((x) * 0x4 + RK3572_BIGCORE_CRU_BASE + 0x300)
#define RK3572_BIGCORE_CLKGATE_CON(x)	((x) * 0x4 + RK3572_BIGCORE_CRU_BASE + 0x800)
#define RK3572_BIGCORE_SOFTRST_CON(x)	((x) * 0x4 + RK3572_BIGCORE_CRU_BASE + 0xa00)
#define RK3572_LITCORE0_CLKSEL_CON(x)	((x) * 0x4 + RK3572_LITCORE0_CRU_BASE + 0x300)
#define RK3572_LITCORE0_CLKGATE_CON(x)	((x) * 0x4 + RK3572_LITCORE0_CRU_BASE + 0x800)
#define RK3572_LITCORE0_SOFTRST_CON(x)	((x) * 0x4 + RK3572_LITCORE0_CRU_BASE + 0xa00)
#define RK3572_LITCORE1_CLKSEL_CON(x)	((x) * 0x4 + RK3572_LITCORE1_CRU_BASE + 0x300)
#define RK3572_LITCORE1_CLKGATE_CON(x)	((x) * 0x4 + RK3572_LITCORE1_CRU_BASE + 0x800)
#define RK3572_LITCORE1_SOFTRST_CON(x)	((x) * 0x4 + RK3572_LITCORE1_CRU_BASE + 0xa00)

enum {
	/* CRU_CLK_SEL8_CON */
	PCLK_TOP_SEL_SHIFT		= 7,
	PCLK_TOP_SEL_MASK		= 3 << PCLK_TOP_SEL_SHIFT,
	PCLK_TOP_SEL_100M		= 0,
	PCLK_TOP_SEL_50M,
	PCLK_TOP_SEL_OSC,

	/* CRU_CLK_SEL9_CON */
	ACLK_TOP_SEL_SHIFT		= 5,
	ACLK_TOP_SEL_MASK		= 3 << ACLK_TOP_SEL_SHIFT,
	ACLK_TOP_SEL_GPLL		= 0,
	ACLK_TOP_SEL_CPLL,
	ACLK_TOP_SEL_AUPLL,
	ACLK_TOP_DIV_SHIFT		= 0,
	ACLK_TOP_DIV_MASK		= 0x1f << ACLK_TOP_DIV_SHIFT,

	/* CRU_CLK_SEL10_CON */
	ACLK_TOP_MID_SEL_SHIFT		= 5,
	ACLK_TOP_MID_SEL_MASK		= 1 << ACLK_TOP_MID_SEL_SHIFT,
	ACLK_TOP_MID_SEL_GPLL		= 0,
	ACLK_TOP_MID_SEL_CPLL,
	ACLK_TOP_MID_DIV_SHIFT		= 0,
	ACLK_TOP_MID_DIV_MASK		= 0x1f << ACLK_TOP_MID_DIV_SHIFT,

	/* CRU_CLK_SEL19_CON */
	HCLK_TOP_SEL_SHIFT		= 2,
	HCLK_TOP_SEL_MASK		= 3 << HCLK_TOP_SEL_SHIFT,
	HCLK_TOP_SEL_200M		= 0,
	HCLK_TOP_SEL_100M,
	HCLK_TOP_SEL_50M,
	HCLK_TOP_SEL_OSC,

	/* CRU_CLK_SEL22_CON */
	CLK_UART_FRAC_NUMERATOR_SHIFT	= 16,
	CLK_UART_FRAC_NUMERATOR_MASK	= 0xffff << 16,
	CLK_UART_FRAC_DENOMINATOR_SHIFT	= 0,
	CLK_UART_FRAC_DENOMINATOR_MASK	= 0xffff,

	/* CRU_CLK_SEL23_CON */
	CLK_UART_SRC_SEL_SHIFT		= 0,
	CLK_UART_SRC_SEL_MASK		= 0x3 << CLK_UART_SRC_SEL_SHIFT,
	CLK_UART_SRC_SEL_GPLL		= 0,
	CLK_UART_SRC_SEL_CPLL,
	CLK_UART_SRC_SEL_AUPLL,
	CLK_UART_SRC_SEL_OSC,

	/* CRU_CLK_SEL33_CON */
	CLK_GMAC0_125M_DIV_SHIFT	= 10,
	CLK_GMAC0_125M_DIV_MASK		= 0x1f << CLK_GMAC0_125M_DIV_SHIFT,

	/* CRU_CLK_SEL34_CON */
	CLK_GMAC1_125M_DIV_SHIFT	= 0,
	CLK_GMAC1_125M_DIV_MASK		= 0x1f << CLK_GMAC1_125M_DIV_SHIFT,

	/* CRU_CLK_SEL38_CON */
	REF_CLK0_OUT_PLL_SEL_SHIFT	= 8,
	REF_CLK0_OUT_PLL_SEL_MASK	= 7 << REF_CLK0_OUT_PLL_SEL_SHIFT,
	REF_CLK0_OUT_PLL_SEL_GPLL	= 0,
	REF_CLK0_OUT_PLL_SEL_CPLL,
	REF_CLK0_OUT_PLL_SEL_SPLL,
	REF_CLK0_OUT_PLL_SEL_AUPLL,
	REF_CLK0_OUT_PLL_SEL_BPLL,
	REF_CLK0_OUT_PLL_SEL_OSC,
	REF_CLK0_OUT_PLL_DIV_SHIFT	= 0,
	REF_CLK0_OUT_PLL_DIV_MASK	= 0xff << REF_CLK0_OUT_PLL_DIV_SHIFT,

	/* CRU_CLK_SEL64_CON */
	ACLK_BUS_ROOT_SEL_SHIFT		= 9,
	ACLK_BUS_ROOT_SEL_MASK		= 1 << ACLK_BUS_ROOT_SEL_SHIFT,
	ACLK_BUS_ROOT_SEL_GPLL		= 0,
	ACLK_BUS_ROOT_SEL_CPLL,
	ACLK_BUS_ROOT_DIV_SHIFT		= 4,
	ACLK_BUS_ROOT_DIV_MASK		= 0x1f << ACLK_BUS_ROOT_DIV_SHIFT,
	PCLK_BUS_ROOT_SEL_SHIFT		= 2,
	PCLK_BUS_ROOT_SEL_MASK		= 3 << PCLK_BUS_ROOT_SEL_SHIFT,
	PCLK_BUS_ROOT_SEL_100M		= 0,
	PCLK_BUS_ROOT_SEL_50M,
	PCLK_BUS_ROOT_SEL_OSC,
	HCLK_BUS_ROOT_SEL_SHIFT		= 0,
	HCLK_BUS_ROOT_SEL_MASK		= 3 << HCLK_BUS_ROOT_SEL_SHIFT,
	HCLK_BUS_ROOT_SEL_200M		= 0,
	HCLK_BUS_ROOT_SEL_100M,
	HCLK_BUS_ROOT_SEL_50M,
	HCLK_BUS_ROOT_SEL_OSC,

	/* CRU_CLK_SEL67_CON */
	CLK_I2C4_SEL_SHIFT		= 13,
	CLK_I2C4_SEL_MASK		= 3 << CLK_I2C4_SEL_SHIFT,
	CLK_I2C3_SEL_SHIFT		= 11,
	CLK_I2C3_SEL_MASK		= 3 << CLK_I2C3_SEL_SHIFT,
	CLK_I2C2_SEL_SHIFT		= 7,
	CLK_I2C2_SEL_MASK		= 3 << CLK_I2C2_SEL_SHIFT,
	CLK_I2C1_SEL_SHIFT		= 7,
	CLK_I2C1_SEL_MASK		= 3 << CLK_I2C1_SEL_SHIFT,
	CLK_I2C_SEL_200M		= 0,
	CLK_I2C_SEL_100M,
	CLK_I2C_SEL_50M,
	CLK_I2C_SEL_OSC,

	/* CRU_CLK_SEL68_CON */
	CLK_I2C9_SEL_SHIFT		= 8,
	CLK_I2C9_SEL_MASK		= 3 << CLK_I2C9_SEL_SHIFT,
	CLK_I2C8_SEL_SHIFT		= 6,
	CLK_I2C8_SEL_MASK		= 3 << CLK_I2C8_SEL_SHIFT,
	CLK_I2C7_SEL_SHIFT		= 4,
	CLK_I2C7_SEL_MASK		= 3 << CLK_I2C7_SEL_SHIFT,
	CLK_I2C6_SEL_SHIFT		= 2,
	CLK_I2C6_SEL_MASK		= 3 << CLK_I2C6_SEL_SHIFT,
	CLK_I2C5_SEL_SHIFT		= 0,
	CLK_I2C5_SEL_MASK		= 3 << CLK_I2C5_SEL_SHIFT,

	/* CRU_CLK_SEL69_CON */
	CLK_SARADC_SEL_SHIFT		= 8,
	CLK_SARADC_SEL_MASK		= 0x3 << CLK_SARADC_SEL_SHIFT,
	CLK_SARADC_SEL_GPLL		= 0,
	CLK_SARADC_SEL_OSC,
	CLK_SARADC_SEL_32K,
	CLK_SARADC_DIV_SHIFT		= 0,
	CLK_SARADC_DIV_MASK		= 0xff << CLK_SARADC_DIV_SHIFT,

	/* CRU_CLK_SEL70_CON */
	CLK_TSADC_DIV_SHIFT		= 0,
	CLK_TSADC_DIV_MASK		= 0xff << CLK_TSADC_DIV_SHIFT,

	/* CRU_CLK_SEL71_CON */
	CLK_UART_SEL_SHIFT		= 8,
	CLK_UART_SEL_MASK		= 7 << CLK_UART_SEL_SHIFT,
	CLK_UART_SEL_GPLL		= 0,
	CLK_UART_SEL_CPLL,
	CLK_UART_SEL_AUPLL,
	CLK_UART_SEL_OSC,
	CLK_UART_SEL_FRAC0,
	CLK_UART_SEL_FRAC1,
	CLK_UART_SEL_FRAC2,
	CLK_UART_DIV_SHIFT		= 0,
	CLK_UART_DIV_MASK		= 0xff << CLK_UART_DIV_SHIFT,

	/* CRU_CLK_SEL81_CON */
	CLK_SPI0_SEL_SHIFT		= 13,
	CLK_SPI0_SEL_MASK		= 3 << CLK_SPI0_SEL_SHIFT,
	CLK_SPI_SEL_300M		= 0,
	CLK_SPI_SEL_200M,
	CLK_SPI_SEL_100M,
	CLK_SPI_SEL_OSC,

	/* CRU_CLK_SEL82_CON */
	CLK_PWM1_SEL_SHIFT		= 8,
	CLK_PWM1_SEL_MASK		= 3 << CLK_PWM1_SEL_SHIFT,
	CLK_PWM_SEL_100M		= 0,
	CLK_PWM_SEL_50M,
	CLK_PWM_SEL_OSC,
	CLK_SPI4_SEL_SHIFT		= 6,
	CLK_SPI4_SEL_MASK		= 3 << CLK_SPI4_SEL_SHIFT,
	CLK_SPI3_SEL_SHIFT		= 4,
	CLK_SPI3_SEL_MASK		= 3 << CLK_SPI3_SEL_SHIFT,
	CLK_SPI2_SEL_SHIFT		= 2,
	CLK_SPI2_SEL_MASK		= 3 << CLK_SPI2_SEL_SHIFT,
	CLK_SPI1_SEL_SHIFT		= 0,
	CLK_SPI1_SEL_MASK		= 3 << CLK_SPI1_SEL_SHIFT,

	/* CRU_CLK_SEL83_CON */
	CLK_PWM2_SEL_SHIFT		= 0,
	CLK_PWM2_SEL_MASK		= 3 << CLK_PWM2_SEL_SHIFT,

	/* CRU_CLK_SEL84_CON */
	DCLK_DECOM_SEL_SHIFT		= 5,
	DCLK_DECOM_SEL_MASK		= 3 << DCLK_DECOM_SEL_SHIFT,
	DCLK_DECOM_SEL_GPLL		= 0,
	DCLK_DECOM_SEL_CPLL,
	DCLK_DECOM_SEL_SPLL,
	DCLK_DECOM_DIV_SHIFT		= 0,
	DCLK_DECOM_DIV_MASK		= 0x1f << DCLK_DECOM_DIV_SHIFT,

	/* CRU_CLK_SEL98_CON */
	CLK_GMAC0_PTP_SEL_SHIFT		= 6,
	CLK_GMAC0_PTP_SEL_MASK		= 1 << CLK_GMAC0_PTP_SEL_SHIFT,
	CLK_GMAC0_PTP_SEL_PRE		= 0,
	CLK_GMAC0_PTP_SEL_IOIN,
	CLK_GMAC0_PTP_PRE_SEL_SHIFT	= 5,
	CLK_GMAC0_PTP_PRE_SEL_MASK	= 1 << CLK_GMAC0_PTP_PRE_SEL_SHIFT,
	CLK_GMAC0_PTP_PRE_SEL_GPLL	= 0,
	CLK_GMAC0_PTP_PRE_SEL_CPLL,
	CLK_GMAC0_PTP_PRE_DIV_SHIFT	= 0,
	CLK_GMAC0_PTP_PRE_DIV_MASK	= 0x1f << CLK_GMAC0_PTP_PRE_DIV_SHIFT,

	/* CRU_CLK_SEL114_CON */
	CLK_GMAC1_PTP_SRC_SEL_SHIFT	= 15,
	CLK_GMAC1_PTP_SRC_SEL_MASK	= 1 << CLK_GMAC1_PTP_SRC_SEL_SHIFT,
	CLK_GMAC1_PTP_SRC_SEL_GPLL	= 0,
	CLK_GMAC1_PTP_SRC_SEL_CPLL,
	CLK_GMAC1_PTP_SRC_DIV_SHIFT	= 10,
	CLK_GMAC1_PTP_SRC_DIV_MASK	= 0x1f << CLK_GMAC1_PTP_SRC_DIV_SHIFT,
	BCLK_EMMC_SEL_SHIFT		= 8,
	BCLK_EMMC_SEL_MASK		= 3 << BCLK_EMMC_SEL_SHIFT,
	BCLK_EMMC_SEL_200M		= 0,
	BCLK_EMMC_SEL_100M,
	BCLK_EMMC_SEL_50M,
	BCLK_EMMC_SEL_OSC,
	CCLK_EMMC_SEL_SHIFT		= 6,
	CCLK_EMMC_SEL_MASK		= 3 << CCLK_EMMC_SEL_SHIFT,
	CCLK_EMMC_SEL_GPLL		= 0,
	CCLK_EMMC_SEL_CPLL,
	CCLK_EMMC_SEL_OSC,
	CCLK_EMMC_DIV_SHIFT		= 0,
	CCLK_EMMC_DIV_MASK		= 0x3f << CCLK_EMMC_DIV_SHIFT,

	/* CRU_CLK_SEL115_CON */
	SCLK_FSPI0_SEL_SHIFT		= 7,
	SCLK_FSPI0_SEL_MASK		= 7 << SCLK_FSPI0_SEL_SHIFT,
	SCLK_FSPI0_SEL_GPLL		= 0,
	SCLK_FSPI0_SEL_CPLL,
	SCLK_FSPI0_SEL_SPLL,
	SCLK_FSPI0_SEL_AUPLL,
	SCLK_FSPI0_SEL_OSC,
	SCLK_FSPI0_DIV_SHIFT		= 1,
	SCLK_FSPI0_DIV_MASK		= 0x3f << SCLK_FSPI0_DIV_SHIFT,
	CLK_GMAC1_PTP_SEL_SHIFT		= 0,
	CLK_GMAC1_PTP_SEL_MASK		= 1 << CLK_GMAC1_PTP_SEL_SHIFT,
	CLK_GMAC1_PTP_SEL_SRC		= 0,
	CLK_GMAC1_PTP_SEL_IOIN,

	/* CRU_CLK_SEL116_CON */
	CCLK_SDMMC1_SRC_SEL_SHIFT	= 6,
	CCLK_SDMMC1_SRC_SEL_MASK	= 3 << CCLK_SDMMC1_SRC_SEL_SHIFT,
	CCLK_SDMMC1_SRC_SEL_GPLL	= 0,
	CCLK_SDMMC1_SRC_SEL_CPLL,
	CCLK_SDMMC1_SRC_SEL_OSC,
	CCLK_SDMMC1_SRC_DIV_SHIFT	= 0,
	CCLK_SDMMC1_SRC_DIV_MASK	= 0x3f << CCLK_SDMMC1_SRC_DIV_SHIFT,

	/* CRU_CLK_SEL121_CON */
	CCLK_SDMMC0_SRC_SEL_SHIFT	= 6,
	CCLK_SDMMC0_SRC_SEL_MASK	= 3 << CCLK_SDMMC0_SRC_SEL_SHIFT,
	CCLK_SDMMC0_SRC_SEL_GPLL	= 0,
	CCLK_SDMMC0_SRC_SEL_CPLL,
	CCLK_SDMMC0_SRC_SEL_OSC,
	CCLK_SDMMC0_SRC_DIV_SHIFT	= 0,
	CCLK_SDMMC0_SRC_DIV_MASK	= 0x3f << CCLK_SDMMC0_SRC_DIV_SHIFT,

	/* CRU_CLK_SEL122_CON */
	SCLK_FSPI1_SEL_SHIFT		= 6,
	SCLK_FSPI1_SEL_MASK		= 7 << SCLK_FSPI1_SEL_SHIFT,
	SCLK_FSPI1_SEL_GPLL		= 0,
	SCLK_FSPI1_SEL_CPLL,
	SCLK_FSPI1_SEL_SPLL,
	SCLK_FSPI1_SEL_AUPLL,
	SCLK_FSPI1_SEL_OSC,
	SCLK_FSPI1_DIV_SHIFT		= 0,
	SCLK_FSPI1_DIV_MASK		= 0x3f << SCLK_FSPI1_DIV_SHIFT,

	/* CRU_CLK_SEL143_CON */
	DCLK_EBC_SRC_SEL_SHIFT		= 13,
	DCLK_EBC_SRC_SEL_MASK		= 7 << DCLK_EBC_SRC_SEL_SHIFT,
	DCLK_EBC_SRC_SEL_GPLL		= 0,
	DCLK_EBC_SRC_SEL_CPLL,
	DCLK_EBC_SRC_SEL_VPLL,
	DCLK_EBC_SRC_SEL_AUPLL,
	DCLK_EBC_SRC_SEL_BPLL,
	DCLK_EBC_SRC_SEL_OSC,

	/* CRU_CLK_SEL144_CON */
	DCLK_EBC_SRC_DIV_SHIFT		= 0,
	DCLK_EBC_SRC_DIV_MASK		= 0x1ff << DCLK_EBC_SRC_DIV_SHIFT,

	/* CRU_CLK_SEL146_CON */
	DCLK_EBC_SEL_SHIFT		= 0,
	DCLK_EBC_SEL_MASK		= 1 << DCLK_EBC_SEL_SHIFT,
	DCLK_EBC_SEL_INT		= 0,
	DCLK_EBC_SEL_FRAC,

	/* CRU_CLK_SEL174_CON */
	PCLK_VOP_ROOT_SEL_SHIFT		= 12,
	PCLK_VOP_ROOT_SEL_MASK		= 3 << PCLK_VOP_ROOT_SEL_SHIFT,
	PCLK_VOP_ROOT_SEL_100M		= 0,
	PCLK_VOP_ROOT_SEL_50M,
	PCLK_VOP_ROOT_SEL_OSC,
	HCLK_VOP_ROOT_SEL_SHIFT		= 10,
	HCLK_VOP_ROOT_SEL_MASK		= 3 << HCLK_VOP_ROOT_SEL_SHIFT,
	HCLK_VOP_ROOT_SEL_200M		= 0,
	HCLK_VOP_ROOT_SEL_100M,
	HCLK_VOP_ROOT_SEL_50M,
	HCLK_VOP_ROOT_SEL_OSC,
	ACLK_VOP_ROOT_SEL_SHIFT		= 5,
	ACLK_VOP_ROOT_SEL_MASK		= 7 << ACLK_VOP_ROOT_SEL_SHIFT,
	ACLK_VOP_ROOT_SEL_GPLL		= 0,
	ACLK_VOP_ROOT_SEL_CPLL,
	ACLK_VOP_ROOT_SEL_AUPLL,
	ACLK_VOP_ROOT_SEL_SPLL,
	ACLK_VOP_ROOT_SEL_BPLL,
	ACLK_VOP_ROOT_DIV_SHIFT		= 0,
	ACLK_VOP_ROOT_DIV_MASK		= 0x1f << ACLK_VOP_ROOT_DIV_SHIFT,

	/* CRU_CLK_SEL175_CON */
	DCLK0_VOP_SRC_SEL_SHIFT		= 8,
	DCLK0_VOP_SRC_SEL_MASK		= 3 << DCLK0_VOP_SRC_SEL_SHIFT,
	DCLK_VOP_SRC_SEL_GPLL		= 0,
	DCLK_VOP_SRC_SEL_CPLL,
	DCLK_VOP_SRC_SEL_VPLL,
	DCLK_VOP_SRC_SEL_BPLL,
	DCLK0_VOP_SRC_DIV_SHIFT		= 0,
	DCLK0_VOP_SRC_DIV_MASK		= 0xff << DCLK0_VOP_SRC_DIV_SHIFT,

	/* CRU_CLK_SEL177_CON */
	DCLK1_VOP_SEL_SHIFT		= 12,
	DCLK1_VOP_SEL_MASK		= 1 << DCLK1_VOP_SEL_SHIFT,
	DCLK0_VOP_SEL_SHIFT		= 11,
	DCLK0_VOP_SEL_MASK		= 1 << DCLK0_VOP_SEL_SHIFT,

	/* CRU_CLK_SEL185_CON */
	ACLK_VO_ROOT_SEL_SHIFT		= 5,
	ACLK_VO_ROOT_SEL_MASK		= 3 << ACLK_VO_ROOT_SEL_SHIFT,
	ACLK_VO_ROOT_SEL_GPLL		= 0,
	ACLK_VO_ROOT_SEL_CPLL,
	ACLK_VO_ROOT_SEL_BPLL,
	ACLK_VO_ROOT_DIV_SHIFT		= 0,
	ACLK_VO_ROOT_DIV_MASK		= 0x1f << ACLK_VO_ROOT_DIV_SHIFT,

	/* PMUCRU_CLK_SEL5_CON */
	CLK_PWM0_SEL_SHIFT		= 0,
	CLK_PWM0_SEL_MASK		= 3 << CLK_PWM0_SEL_SHIFT,

	/* PMUCRU_CLK_SEL6_CON */
	CLK_I2C0_SEL_SHIFT		= 7,
	CLK_I2C0_SEL_MASK		= 3 << CLK_I2C0_SEL_SHIFT,

	/* PMUCRU_CLK_SEL8_CON */
	CLK_UART1_SEL_SHIFT		= 0,
	CLK_UART1_SEL_MASK		= 3 << CLK_UART1_SEL_SHIFT,
	CLK_UART1_SEL_TOP		= 0,
	CLK_UART1_SEL_OSC,
};
#endif
