#
# (C) Copyright 2008-2017 Fuzhou Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_DRM_ROCKCHIP_DW_HDMI) += rockchip_dw_hdmi.o dw_hdmi.o
obj-$(CONFIG_RKCHIP_INNO_HDMI_PHY) += rockchip-inno-hdmi-phy.o
obj-$(CONFIG_ROCKCHIP_DRM_TVE) += rockchip_drm_tve.o
obj-$(CONFIG_ROCKCHIP_PANEL) += rk1000.o
