#
# (C) Copyright 2008-2015 Fuzhou Rockchip Electronics Co., Ltd
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_ROCKCHIP_DW_HDMI) += rockchip_dw_hdmi.o rockchip_dw_hdmi_reg.o rk_edid.o
