# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_DM_POWER_DELIVERY) += power_delivery_uclass.o
obj-$(CONFIG_TYPEC_PD_TCPM) += tcpm.o
obj-$(CONFIG_TYPEC_PD_FUSB302) += fusb302.o
obj-$(CONFIG_TYPEC_PD_TCPCI) += tcpci.o
obj-$(CONFIG_TYPEC_PD_HUSB311) += tcpci_husb311.o
