#********************************************************************************
#       COPYRIGHT (c)   2013 BY ROCK-CHIP FUZHOU
#           --  ALL RIGHTS RESERVED  --
#File Name:
#Author:
#Created:
#Modified:
#Revision:       1.00
#********************************************************************************

obj-$(CONFIG_RK616) +=  rk616.o
