#
# Copyright 2008-2015 Fuzhou Rockchip Electronics Co., Ltd
# Peter, Software Engineering, <superpeter.cai@gmail.com>.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += usbdev_bc.o
obj-$(CONFIG_CHARGER_BQ25700) += bq25700_charger.o
