#!/bin/bash
#
# Copyright (c) 2019 Fuzhou Rockchip Electronics Co., Ltd
#
# SPDX-License-Identifier: GPL-2.0
#

set -e

SKIP_CHECK=
FILTERED_ARGS=()
for arg in "$@"; do
	if [ "${arg}" = "-i" ]; then
		SKIP_CHECK=y
	else
		FILTERED_ARGS+=("${arg}")
	fi
done

INPUT_FILE=${FILTERED_ARGS[0]}
TPL_SPL=${FILTERED_ARGS[1]}

echo
if [ ${#FILTERED_ARGS[@]} -eq 0 ] || [ ${#FILTERED_ARGS[@]} -gt 2 ]; then
	echo "Usage: "
	echo "	./scripts/stacktrace.sh <file> <type>"
	echo
	echo "Param:"
	echo "	<file>: stacktrace info file"
	echo "	<type>: none, spl, tpl"
	echo "	-i: ignore backtrace build validation"
	echo
	echo "Example:"
	echo "	./scripts/stacktrace.sh ./dump.txt"
	echo "	./scripts/stacktrace.sh ./dump.txt tpl"
	echo "	./scripts/stacktrace.sh ./dump.txt spl"
	echo
	exit 1
elif [ ! -f "${INPUT_FILE}" ]; then
	echo "ERROR: No ${INPUT_FILE}"
	exit 1
fi

case "${TPL_SPL}" in
tpl)
	SYM_NAME=u-boot-tpl.sym
	ELF_ARGS=(elf-S tpl)
	EXPECTED_BUILD=tpl
	;;
spl)
	SYM_NAME=u-boot-spl.sym
	ELF_ARGS=(elf-S spl)
	EXPECTED_BUILD=spl
	;;
""|none)
	SYM_NAME=u-boot.sym
	ELF_ARGS=(elf-S)
	EXPECTED_BUILD=uboot
	;;
*)
	echo "ERROR: Invalid type '${TPL_SPL}', expected none, spl, or tpl"
	exit 1
	;;
esac

mapfile -t SYM_FILES < <(find . -name "${SYM_NAME}" -type f)
if [ ${#SYM_FILES[@]} -eq 0 ]; then
	echo "ERROR: No ${SYM_NAME}"
	exit 1
elif [ ${#SYM_FILES[@]} -gt 1 ]; then
	echo "ERROR: Multiple ${SYM_NAME} files found:"
	printf '       %s\n' "${SYM_FILES[@]}"
	exit 1
fi
SYM_FILE=${SYM_FILES[0]}

dos2unix "${INPUT_FILE}" 2>/dev/null

BOARD_INFO=
if grep -Fqx '=== Backtrace ===' "${INPUT_FILE}"; then
	BOARD_INFO=$(awk '$0 == "=== Backtrace ===" { getline; print; exit }' "${INPUT_FILE}")
	if [[ "${BOARD_INFO}" == "U-Boot TPL "* ]]; then
		INPUT_BUILD=tpl
	elif [[ "${BOARD_INFO}" == "U-Boot SPL "* ]]; then
		INPUT_BUILD=spl
	elif [[ "${BOARD_INFO}" == "USB-PLUG "* ]]; then
		INPUT_BUILD=uboot
	elif [[ "${BOARD_INFO}" == "U-Boot "* ]]; then
		INPUT_BUILD=uboot
	else
		echo "ERROR: Unknown build information: ${BOARD_INFO}."
		exit 1
	fi
	if [ "${INPUT_BUILD}" != "${EXPECTED_BUILD}" ]; then
		echo "ERROR: Backtrace build type '${INPUT_BUILD}' does not match requested type '${EXPECTED_BUILD}'."
		exit 1
	fi
elif [ -z "${SKIP_CHECK}" ]; then
	echo "ERROR: Please copy board panic info starting from '=== Backtrace ==='"
	exit 1
fi

if [ -z "${SKIP_CHECK}" ]; then
	VERSION_FILE=include/generated/version_autogenerated.h
	if [ ! -f "${VERSION_FILE}" ]; then
		echo "ERROR: No ${VERSION_FILE}."
		echo "       Please rebuild U-Boot before $0."
		exit 1
	fi

	PLAIN_VERSION=$(sed -n 's/^#define PLAIN_VERSION "\(.*\)"$/\1/p' "${VERSION_FILE}")
	BOARD_COMMIT=$(printf '%s\n' "${BOARD_INFO}" |
		awk 'match($0, /-g[[:xdigit:]]+/) {
			print substr($0, RSTART + 2, RLENGTH - 2);
			exit
		}')
	PLAIN_COMMIT=$(printf '%s\n' "${PLAIN_VERSION}" |
		awk 'match($0, /-g[[:xdigit:]]+/) {
			print substr($0, RSTART + 2, RLENGTH - 2);
			exit
		}')
	LOCAL_COMMIT=$(git rev-parse --verify HEAD)
	if [ -z "${PLAIN_VERSION}" ]; then
		echo "ERROR: Failed to get PLAIN_VERSION from ${VERSION_FILE}."
		exit 1
	elif [[ "${BOARD_INFO}" == *-dirty* ]]; then
		echo "ERROR: Dirty build Image on board is not allowed:"
		echo "       ${BOARD_INFO}."
		exit 1
	elif grep -Fq -- '-dirty' "${VERSION_FILE}"; then
		echo "ERROR: Current dirty build is not allowed: '${PLAIN_VERSION}'"
		echo "       please remove local changes and rebuild U-Boot before $0."
		exit 1
	fi

	if [ -n "${BOARD_COMMIT}" ]; then
		if [ "${PLAIN_COMMIT}" != "${BOARD_COMMIT}" ]; then
			echo "ERROR: Current build commit '${PLAIN_COMMIT}' does not match board commit '${BOARD_COMMIT}'."
			echo "       Please checkout and rebuild U-Boot on commit ${BOARD_COMMIT} before $0."
			exit 1
		elif [[ "${LOCAL_COMMIT}" != "${BOARD_COMMIT}"* ]]; then
			echo "ERROR: Current HEAD commit '${LOCAL_COMMIT}' does not match board commit '${BOARD_COMMIT}'."
			echo "       Please checkout and rebuild U-Boot on commit ${BOARD_COMMIT} before $0."
			exit 1
		fi
	else
		echo "ERROR: No commit id from board info: ${BOARD_INFO}."
		exit 1
	fi
fi

SORTED_SYM_FILE=$(mktemp)
trap 'rm -f "${SORTED_SYM_FILE}"' EXIT
sort "${SYM_FILE}" > "${SORTED_SYM_FILE}"

function print_symbol()
{
	local frame_pc_str=$1
	local output_type=$2

	awk -v frame_pc_str="${frame_pc_str}" -v output_type="${output_type}" '
	function print_match() {
		if (output_type == "call")
			printf("%s+0x%x/0x%x      ", fname, frame_pc-fpc, fsize);
		else
			printf("%s+0x%x/0x%x\n", fname, frame_pc-fpc, fsize);
	}
	BEGIN {
		frame_pc=strtonum(frame_pc_str);
	}
	/\.text/ {
		symbol_pc=strtonum("0x"$1);
		if (symbol_pc > frame_pc) {
			print_match();
			printed=1;
			exit
		}
		fname=$NF;
		fsize=strtonum("0x"$5);
		fpc=symbol_pc;
		have_symbol=1;
	}
	END {
		if (!printed && have_symbol)
			print_match();
	}' "${SORTED_SYM_FILE}"
}

echo
echo "SYMBOL File: ${SYM_FILE}"
echo
# Print the exception context before the resolved call trace.
awk '
!in_backtrace && $0 == "=== Backtrace ===" {
	in_backtrace=1;
	next
}
in_backtrace && $0 == "Call trace:" {
	for (i = 0; i < line_count; i++)
		print lines[i];
	exit
}
in_backtrace {
	lines[line_count++]=$0;
}' "${INPUT_FILE}"

function print_exception_reason()
{
	awk '
	BEGIN {
		reason[0]  = "an unknown reason";
		reason[1]  = "a WFI or WFE instruction";
		reason[3]  = "an MCR or MRC access";
		reason[4]  = "an MCRR or MRRC access";
		reason[5]  = "an MCR or MRC access";
		reason[6]  = "an LDC or STC access to CP14";
		reason[7]  = "an access to an Advanced SIMD or floating-point register, resulting from CPACR_EL1.FPEN or CPTR_ELx.TFP";
		reason[8]  = "an MCR or MRC access";
		reason[10] = "HVC or SVC instruction execution";
		reason[12] = "an MCRR or MRRC access";
		reason[14] = "an Illegal execution state, or a PC or SP alignment fault";
		reason[18] = "HVC or SVC instruction execution";
		reason[19] = "SMC instruction execution in AArch32 state";
		reason[21] = "HVC or SVC instruction execution";
		reason[22] = "HVC or SVC instruction execution";
		reason[23] = "SMC instruction execution in AArch64 state";
		reason[24] = "MSR, MRS, or System instruction execution in AArch64 state";
		reason[31] = "IMPLEMENTATION DEFINED exception to EL3";
		reason[32] = "an Instruction abort";
		reason[33] = "an Instruction abort";
		reason[34] = "an Illegal execution state, or a PC or SP alignment fault";
		reason[36] = "a Data abort, from lower exception level";
		reason[37] = "a Data abort, from current exception level";
		reason[38] = "an Illegal execution state, or a PC or SP alignment fault";
		reason[40] = "a trapped Floating-point exception";
		reason[44] = "a trapped Floating-point exception";
		reason[47] = "SError interrupt";
		reason[48] = "a Breakpoint or Vector Catch debug event";
		reason[49] = "a Breakpoint or Vector Catch debug event";
		reason[50] = "a Software Step debug event";
		reason[51] = "a Software Step debug event";
		reason[52] = "a Watchpoint debug event";
		reason[53] = "a Watchpoint debug event";
		reason[56] = "execution of a Software Breakpoint instruction";
		reason[60] = "execution of a Software Breakpoint instruction";
	}
	/^ESR:[[:space:]]/ {
		if (match($0, /ec=[0-9]+/)) {
			ec=substr($0, RSTART + 3, RLENGTH - 3) + 0;
			if (!(ec in reason))
				ec=0;
			printf("Reason: Exception from %s\n", reason[ec]);
			exit;
		}
	}' "${INPUT_FILE}"

	echo
}

if [ "${TPL_SPL}" = "spl" ] || [ "${TPL_SPL}" = "tpl" ]; then
	print_exception_reason
fi

# Parse PC and LR
echo "Call trace:"
grep '\[< ' "${INPUT_FILE}" | grep '>\]' | grep -E 'PC|LR' | while read -r line
do
	echo -n " ${line}  "

	frame_pc_str=$(awk '{ print "0x"$3 }' <<< "${line}")
	print_symbol "${frame_pc_str}" call

	func_path=$(./make.sh "${frame_pc_str}" | awk '{ print $1 }' | sed -n "/home/p")
	func_path=${func_path##*boot/}
	echo "${func_path}"
done
echo

# Parse stack
echo "Stack:"
grep '\[< ' "${INPUT_FILE}" | grep '>\]' | grep -Ev 'PC|LR' | while read -r line
do
	echo -n "       ${line}  "

	frame_pc_str=$(awk '{ print "0x"$2 }' <<< "${line}")
	print_symbol "${frame_pc_str}" stack
done
echo

# PC instruction
echo "PC Surrounding Instructions:"
line=$(grep '\[< ' "${INPUT_FILE}" | grep '>\]' | grep 'PC')
frame_pc_str=$(awk '{ print "0x"$3 }' <<< "${line}")
frame_pc_dec=$(awk '{ print strtonum("0x"$3); }' <<< "${line}")
# Handle Thumb instr
if (( frame_pc_dec % 2 != 0 )); then
	frame_pc_dec=$((frame_pc_dec - 1))
fi
frame_pc_hex=$(printf 'obase=16;%s\n' "${frame_pc_dec}" | bc | tr '[:upper:]' '[:lower:]')
PC_INSTR=$(./make.sh "${ELF_ARGS[@]}" | grep -16 -m 1 "${frame_pc_hex}:" |
	awk -v pc="${frame_pc_hex}" '
	{
		instruction=$0;
		sub(/^[[:space:]]*/, "", instruction);
		if (!marked && match(instruction, /^[[:xdigit:]]+:/)) {
			address=substr(instruction, 1, RLENGTH - 1);
			if (strtonum("0x" address) == strtonum("0x" pc)) {
				leading=match($0, /[^[:space:]]/) - 1;
				if (leading > 0)
					$0=substr($0, 1, leading - 1) "*" substr($0, leading + 1);
				else
					$0="*" $0;
				marked=1;
			}
		}
		print;
	}')
echo "${PC_INSTR}"
echo
