#
# Copyright (C) 2012 Samsung Electronics
# Lukasz Majewski <l.majewski@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_POWER_LTC3676) += pmic_ltc3676.o
obj-$(CONFIG_POWER_MAX8998) += pmic_max8998.o
obj-$(CONFIG_POWER_MAX8997) += pmic_max8997.o
obj-$(CONFIG_POWER_MUIC_MAX8997) += muic_max8997.o
obj-$(CONFIG_POWER_MAX77686) += pmic_max77686.o
obj-$(CONFIG_POWER_PFUZE100) += pmic_pfuze100.o
obj-$(CONFIG_POWER_TPS65090_I2C) += pmic_tps65090.o
obj-$(CONFIG_POWER_TPS65090_EC) += pmic_tps65090_ec.o
obj-$(CONFIG_POWER_TPS65217) += pmic_tps65217.o
obj-$(CONFIG_POWER_TPS65218) += pmic_tps65218.o
obj-$(CONFIG_POWER_TPS65910) += pmic_tps65910.o
obj-$(CONFIG_POWER_RK_SAMPLE) += pmic_rk_sample.o
obj-$(CONFIG_POWER_RK808) += pmic_rk808.o
obj-$(CONFIG_POWER_RK818) += pmic_rk816.o
obj-$(CONFIG_POWER_RK818) += pmic_rk818.o
obj-$(CONFIG_POWER_ACT8846) += pmic_act8846.o
obj-$(CONFIG_POWER_ACT8931) += pmic_act8931.o
obj-$(CONFIG_POWER_RICOH619) += pmic_ricoh619.o
obj-$(CONFIG_POWER_RT5025) += pmic_rt5025.o
obj-$(CONFIG_POWER_RT5036) += pmic_rt5036.o
