#
# (C) Copyright 2008-2015 Fuzhou Rockchip Electronics Co., Ltd
# Peter, Software Engineering, <superpeter.cai@gmail.com>.
#
# SPDX-License-Identifier:	GPL-2.0+
#
obj-y	+= cpu.o
obj-y	+= timer.o
obj-y	+= clock.o
obj-y	+= lowlevel_init.o
obj-y	+= irqs.o
obj-y	+= ddr.o
obj-y   += iomux.o
obj-y   += reset.o

obj-$(CONFIG_PM_SUBSYSTEM)	+= pm.o
obj-$(CONFIG_RK_PL330_DMAC)	+= pl330.o dma.o
obj-$(CONFIG_RK_PSCI)	+= psci.o
obj-$(CONFIG_RK_GMAC)	+= gmac.o
