#********************************************************************************
#		COPYRIGHT (c)   2013 BY ROCK-CHIP FUZHOU
#			--  ALL RIGHTS RESERVED  --
#File Name:	
#Author:         
#Created:        
#Modified:
#Revision:       1.00
#********************************************************************************

obj-y	+= cpu.o
obj-y	+= board.o
obj-y	+= timer.o
#obj-y	+= clock.o
obj-y	+= interrupts.o
#obj-y	+= intc.o

obj-y	+= cache.o
obj-y	+= lowlevel_init.o
