#
# (C) Copyright 2008-2015 Rockchip Electronics
# Peter, Software Engineering, <superpeter.cai@gmail.com>.
#
# SPDX-License-Identifier:	GPL-2.0+
#
obj-y	+= cpu.o
obj-y	+= timer.o
obj-y	+= clock.o
obj-y	+= lowlevel_init.o
obj-y	+= irqs.o
obj-y	+= ddr.o
obj-y   += iomux.o
obj-y   += reset.o
obj-y	+= pm.o

obj-$(CONFIG_RK_PL330)	+= pl330.o
obj-$(CONFIG_RK_DMAC)	+= dma.o

obj-$(CONFIG_RK_PWM)   += pwm.o
