#
# (C) Copyright 2008-2015 Fuzhou Rockchip Electronics Co., Ltd
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_RK32_DSI) +=  rk32_mipi_dsi.o mipi_dsi.o
