#********************************************************************************
#		COPYRIGHT (c)   2013 BY ROCK-CHIP FUZHOU
#			--  ALL RIGHTS RESERVED  --
#File Name:	
#Author:         
#Created:        
#Modified:
#Revision:       1.00
#********************************************************************************

obj-y += crc.o
obj-y += rkimage.o
obj-y += idblock.o
obj-y += fastboot.o
obj-y	+= key.o
obj-y += enter_recovery.o
obj-y += parameter.o
obj-y += rsa.o
obj-y += sha.o
obj-y += rc4_enc.o
obj-y += boot.o
obj-y += std_commod.o
ifdef CONFIG_NAND
obj-y += storage_nand.o
else
obj-y += storage.o
endif

obj-y += chipDepend.o


