#********************************************************************************
#		COPYRIGHT (c)   2013 BY ROCK-CHIP FUZHOU
#			--  ALL RIGHTS RESERVED  --
#File Name:	
#Author:         
#Created:        
#Modified:
#Revision:       1.00
#********************************************************************************

obj-y := $(BOARD).o
obj-y += crc.o
obj-y += rkimage.o
obj-y += rkloader.o
obj-y += fastboot.o
obj-y	+= key.o
obj-$(CONFIG_ZYF) += bootloader.o
obj-$(CONFIG_ZYF) += enter_recovery.o
obj-$(CONFIG_ZYF) += parameter.o
obj-$(CONFIG_ZYF) += rsa.o
obj-$(CONFIG_ZYF) += sha.o
obj-$(CONFIG_ZYF) += emmc/hw_MMC.o
obj-$(CONFIG_ZYF) += emmc/hw_SD.o
obj-$(CONFIG_ZYF) += emmc/hw_SDController.o
obj-$(CONFIG_ZYF) += emmc/hw_SDM.o
obj-$(CONFIG_ZYF) += emmc/hw_SDOsAdapt.o
obj-$(CONFIG_ZYF) += emmc/hw_SDPlatAdapt.o
obj-$(CONFIG_ZYF) += emmc/sdmmcBoot.o
obj-$(CONFIG_ZYF) += rc4_enc.o
obj-$(CONFIG_ZYF) += rockusb/Chap_9.o
obj-$(CONFIG_ZYF) += rockusb/D12ci.o
obj-$(CONFIG_ZYF) += rockusb/rockusb.o
obj-$(CONFIG_ZYF) += rockusb/usbCtrl.o
obj-$(CONFIG_ZYF) += rockusb/usbIsr.o
obj-$(CONFIG_ZYF) += boot.o
obj-$(CONFIG_ZYF) += GetIdBlockInfo.o
obj-$(CONFIG_ZYF) += std_commod.o
obj-$(CONFIG_ZYF) += storage.o
obj-$(CONFIG_ZYF) += chipDepend.o

