#
# (C) Copyright 2023 Rockchip Electronics Co., Ltd.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_CMD_DDR_TOOL) += ddr_tool_common.o ddr_tool_mp.o io_map.o

obj-$(CONFIG_CMD_MEMTESTER) += memtester/
obj-$(CONFIG_CMD_STRESSAPPTEST) += stressapptest/
