#
# (C) Copyright 2008 - 2014 Rockchip Electronics
# Peter, Software Engineering, <superpeter.cai@gmail.com>.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y := $(BOARD).o

obj-$(CONFIG_BOARD_DEMO) += demo.o
