#
# (C) Copyright 2008 - 2015 Fuzhou Rockchip Electronics Co., Ltd
# Peter, Software Engineering, <superpeter.cai@gmail.com>.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y := $(BOARD).o

obj-$(CONFIG_BOARD_DEMO) += demo.o
obj-$(CONFIG_RK_IO_TOOL) += io_tool.o
