# SPDX-License-Identifier: GPL-2.0+

obj-y += core.o
obj-y += reserved_shm.o
obj-y += supplicant.o
obj-$(CONFIG_DM_I2C) += i2c.o
obj-$(CONFIG_SUPPORT_EMMC_RPMB) += rpmb.o
obj-$(CONFIG_ROCKCHIP_UFS_RPMB) += ufs_rpmb.o
obj-$(CONFIG_ARCH_ROCKCHIP) += rockchip/
